spring:
  application:
    name: location-service
  profiles:
    active: dev

  config:
    import: configserver:http://localhost:8888

  cloud:
    config:
      uri: http://localhost:8888/
      username: 
      password: 
      label: main

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 

