server:
  port: 8082

spring:
  application:
    name: location-service
  profiles:
    active: ${QS_ENV}

  config:
    import: configserver:http://config-server.booking-app:8888

  cloud:
    config:
      uri: http://config-server.booking-app:8888
      name: location-service,application
      username: ${QS_USERNAME}
      password: ${QS_PASSWORD}
      label: main
      fail-fast: true
